# Sleep Cannabis Alcohol Study

- Merging merged actigraphy data from the 4 studies with the scored (scrubbed) actigraphy data from each study

Notes: 
- Use scored data for start and stop times.
- Use the actigraphy data for determining sleep metrics
- Calculate sleep biomarkers for: 
  1. First 1/2 of sleep night i.e., start sleep to mid-sleep)
  2. first 4-h of sleep (sleep start to sleep start + 4h)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [2]:
actigraphy_df = pd.read_csv('/Users/thomasgooding/Desktop/Rutgers_Sleep_Cannabis_Alcohol_study/Data_analysis/full_actigraphy_df_cleaned.csv')

actigraphy_df.head()

,Unnamed: 0,subject_id,study,date,time,time_epoch,date_time24,off_wrist_status,activity,marker,sleep/wake,interval_status,participant
0,0,DXA_174,DXA,3/27/2025,12:49:00 PM,769,2025-03-27 12:49:00,0,NaN,0.0,NaN,ACTIVE,dxa174_3_27_2025_12_49_00_pm_174_24hr_ah
1,1,DXA_174,DXA,3/27/2025,12:50:00 PM,770,2025-03-27 12:50:00,0,NaN,0.0,NaN,ACTIVE,dxa174_3_27_2025_12_49_00_pm_174_24hr_ah
2,2,DXA_174,DXA,3/27/2025,12:51:00 PM,771,2025-03-27 12:51:00,0,NaN,0.0,NaN,ACTIVE,dxa174_3_27_2025_12_49_00_pm_174_24hr_ah
3,3,DXA_174,DXA,3/27/2025,12:52:00 PM,772,2025-03-27 12:52:00,0,NaN,0.0,NaN,ACTIVE,dxa174_3_27_2025_12_49_00_pm_174_24hr_ah
4,4,DXA_174,DXA,3/27/2025,12:53:00 PM,773,2025-03-27 12:53:00,0,NaN,0.0,NaN,ACTIVE,dxa174_3_27_2025_12_49_00_pm_174_24hr_ah

In [3]:
scored_sleep_df = pd.read_excel('/Users/thomasgooding/Desktop/Rutgers_Sleep_Cannabis_Alcohol_study/Data_analysis/sleep_merged_df_cleaned_062326.xlsx')

scored_sleep_df.head()

,Unnamed: 0,subject_id,passcode,interval_type,interval#,night,start_date,start_day,start_time,end_date,...,fragmentation,flag_actigraph,study,semester,start_datetime,end_datetime,time_diff,tst_min,sleep_mid_dt,sleep_onset_plus4h
0,0,DXA_001,DXA001,Sleep,1,Friday,2019-09-20,Fri,23:21:00,2019-09-21,...,20.28,NaN,DXA,NaN,2019-09-20 23:21:00,2019-09-21 07:56:00,0.357639,515.0,2019-09-21 03:38:30,2019-09-21 03:21:00
1,1,DXA_001,DXA001,Sleep,2,Saturday,NaT,NaN,NaN,NaT,...,NaN,EXCLUDED - >15% of the day off-wrist,DXA,NaN,NaT,NaT,NaN,NaN,NaT,NaT
2,2,DXA_001,DXA001,Sleep,3,Sunday,2019-09-22,Sun,21:42:00,2019-09-23,...,20.75,NaN,DXA,NaN,2019-09-22 21:42:00,2019-09-23 08:30:00,0.450000,648.0,2019-09-23 03:06:00,2019-09-23 01:42:00
3,3,DXA_001,DXA001,Sleep,4,Monday,2019-09-23,Mon,22:21:00,2019-09-24,...,28.54,NaN,DXA,NaN,2019-09-23 22:21:00,2019-09-24 07:49:00,0.394444,568.0,2019-09-24 03:05:00,2019-09-24 02:21:00
4,4,DXA_001,DXA001,Sleep,5,Tuesday,2019-09-25,Wed,00:29:00,2019-09-25,...,17.80,NaN,DXA,NaN,2019-09-25 00:29:00,2019-09-25 08:20:00,0.327083,471.0,2019-09-25 04:24:30,2019-09-25 04:29:00